### ISSUE TITLE
unable to locate package libturbojpeg

### ISSUE THREAD

**Issue by brant203** [OpenKinect/libfreenect2#209] opened 2015-04-16 04:33 UTC
When trying to install dependencies by using "sudo apt-get install -y build-essential libturbojpeg libtool autoconf libudev-dev cmake mesa-common-dev freeglut3-dev libxrandr-dev doxygen libxi-dev libopencv-dev automake" I get the error "unable to locate packge libturbojpeg." Is there any way to fix this?
edit: I am trying to get this to work on a raspberry pi running rasbian.

**Comment by xlz** [comment] 2015-04-16 05:08
apt-get install libjpeg-turbo8-dev

**Comment by brant203** [comment] 2015-04-16 06:08
I'm getting the same error. It is important for me to note that I am trying to do this on a raspberry pi running rasbian.

**Comment by xlz** [comment] 2015-04-16 06:12
Try with apt-file:

`sudo apt-get install apt-file && sudo apt-file update && apt-file search libturbojpeg.so`

**Comment by brant203** [comment] 2015-04-16 06:39
apt-file search libturbojpeg.so did not return any results. Does this mean that there are no packages with the libturbojpeg.so file in it? Do I need to add a repo or something?

**Comment by wiedemeyer** [comment] 2015-04-16 06:48
@brant203: As far as I know the raspberry pi has only USB 2.0. And from our experience the Kinect2 requires a USB 3.0 port to work.

**Comment by brant203** [comment] 2015-04-16 06:54
I thought usb 3.0 is backwards compatible.

**Comment by wiedemeyer** [comment] 2015-04-16 06:56
You can plug it in, it will be detected, but you probably won't receive any data.

**Comment by brant203** [comment] 2015-04-16 07:08
hmmm. Is there any way to make it work that you know of?

**Comment by wiedemeyer** [comment] 2015-04-16 07:12
Normally I would suggest to get a PCIe USB 3.0 controller card. But that won't work with the raspberry pi.

**Comment by brant203** [comment] 2015-04-16 07:17
Is there a way to use the GPIO pins?

**Comment by wiedemeyer** [comment] 2015-04-16 07:39
probably no.

**Comment by brant203** [comment] 2015-04-16 07:42
hmmm. ok so it is for sure that I will get no data if i try to use this on my pi?

**Comment by wiedemeyer** [comment] 2015-04-16 08:04
You could try, but the chances for it to not work are pretty high.

**Comment by floe** [comment] 2015-04-16 08:26
It's 100% sure that the Kinect v2/One will not work with any Raspberry Pi. You need an embedded board with native USB3 support, such as the Arndale boards or the Odroid-XU. Even then, nobody has tested these yet AFAIK.

**Comment by floe** [comment] 2015-04-23 09:14
BTW, to address the original bug regarding libturbojpeg.so, this is very likely a duplicate of #36 - closing.

**Closed by floe** 2015-04-23 09:14 UTC
Labels: bug, build, question

**Comment by baomin** [comment] 2017-11-18 02:04
sudo apt-get install apt-file && sudo apt-file update && apt-file search libturbojpeg.so
