### ISSUE TITLE
Mic works but camera doesn't

### ISSUE THREAD

**Issue by gabrielbelli** [OpenKinect/libfreenect2#1126] opened 2020-06-30 14:58 UTC
![image](https://user-images.githubusercontent.com/14808000/86141116-106c9b00-bac8-11ea-8da8-c40018a480a8.png)

![image](https://user-images.githubusercontent.com/14808000/86141280-3eea7600-bac8-11ea-9baf-83db6ba92c37.png)

lsusb -t
![image](https://user-images.githubusercontent.com/14808000/86141483-7bb66d00-bac8-11ea-96cb-fca9f9a98a9f.png)

lsusb
![image](https://user-images.githubusercontent.com/14808000/86141623-a4d6fd80-bac8-11ea-92d4-d94161acafce.png)

Protonnect
![image](https://user-images.githubusercontent.com/14808000/86141717-c3d58f80-bac8-11ea-905c-b38c911c64b1.png)

Download all from AUR

**Comment by floe** [comment] 2020-07-01 17:51
Duplicate of #1102, see #946 for potential solution.

**Closed as completed by floe** 2020-07-01 17:51 UTC
