### ISSUE TITLE
Ubuntu 14.04.2 libfreenect.so does not compile anymore

### ISSUE THREAD

**Issue by Lyptik** [OpenKinect/libfreenect2#228] opened 2015-05-11 00:47 UTC
Hello,

I'm on Ubuntu 14.04.2 on commit : 585d4c4bbfc3bc7edb2e664148a8ce183e269b1a

libfreenect.so does not compile (actually link) anymore, I get this error :

Linking CXX shared library lib/libfreenect2.so
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libturbojpeg.a(libturbojpeg_la-turbojpeg.o): relocation R_X86_64_32 against `.data' can not be used when making a shared object; recompile with -fPIC
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libturbojpeg.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
make[2]: *** [lib/libfreenect2.so] Error 1

I have libturbojpeg from the repo :

ii  libjpeg-turbo8:amd64                  1.3.0-0ubuntu2                             amd64        IJG JPEG compliant runtime library.
ii  libjpeg-turbo8-dev:amd64              1.3.0-0ubuntu2                             amd64        Development files for the IJG JPEG library
ii  libturbojpeg:amd64                    1.3.0-0ubuntu2                             amd64        IJG JPEG compliant runtime library.

Do I have to compile libturbojpeg with -fPIC starting from now ?

All the best

**Comment by floe** [comment] 2015-05-11 06:06
This is a duplicate of #36, please see there for workaround.

**Closed by floe** 2015-05-11 06:06 UTC
