### ISSUE TITLE
Question about Depth range

### ISSUE THREAD

**Issue by MasWag** [OpenKinect/libfreenect2#152] opened 2015-02-03 07:55 UTC
Hello all

I am using libfreenect2 with OpenCL and it seems no point further than 4.5m can be seen. But with Microsoft SDK, I cound see about 8m distant point.Is this expected behavior?

This is my environment

* OS : Ubuntu 14.10
* CPU : Intel(R) Core(TM) i7-3630QM 
* GPU : NVIDIA Corporation GF108GLM

Regards,
Masaki Waga

**Comment by tlind** [comment] 2015-02-03 18:13
Looks like a duplicate of this issue: #143

**Comment by MasWag** [comment] 2015-02-04 03:25
Sorry,I didn't read it. I tried and it works well. 
Thanks.

**Closed** 2015-02-04 03:26 UTC
