### ISSUE TITLE
OpenCL compilation fail on Ubuntu 14.04

### ISSUE THREAD

**Issue by ricardborras** [OpenKinect/libfreenect2#139] opened 2015-01-26 14:02 UTC
Protonect with OpenCL enabled (as detected by cmake CMakeLists) fails to compile due to SSE instructions not enabled. To solve it, I added this lines

set(CMAKE_C_FLAGS ${CMAKE_C_FLAGS} "-msse3") 
set(CMAKE_CXX_FLAGS ${CMAKE_CXX_FLAGS} "-msse3")

into CMakeLists.txt (inside IF(ENABLE_OPENCL AND OPENCL_FOUND))

**Comment by floe** [comment] 2015-02-10 17:05
For Intel GPUs, this works for me even without the additional compiler flags. Are you using an NVidia GPU?

**Comment by ricardborras** [comment] 2015-02-22 07:40
No, I am using a Intel Express embedded graphic card

**Comment by xlz** [comment] 2015-05-19 17:49
Please provide specific error messages during failure.

**Comment by xlz** [comment] 2015-10-16 04:49
Fixed by #429. This was caused by direct usage of _mm_mfence() in old cl.hpp.

**Comment by floe** [comment] 2015-11-06 12:04
Should be fixed by #429, please re-test with latest master and re-open if necessary.

**Closed by floe** 2015-11-06 12:04 UTC
Labels: enhancement
