### ISSUE TITLE
Record the RGB and IR image from the libfreenect2

### ISSUE THREAD

**Issue by cforntu** [OpenKinect/libfreenect2#691] opened 2016-07-20 06:58 UTC
Hello, now we can see the color and ir image from the protonect source code. Could anyone tell me how to modify the code to save the color and IR image?

Additional Information:

**Comment by robozo** [comment] 2016-07-21 15:54
if someone has done this, it would save me some time, as this is this weekend's project.
the problem is, it's a lot of data.  i plan to save the point cloud, plus color data, which is around 45 MB/sec at 30 fps.  might be able to save to SSD disk at that rate, more likely save to memory.
saving the uncompressed RGB is too huge, more like 250 MB/sec.
might be able to save the raw jpeg, but then would have to dig into the "listener" code, rather than just modifying protonect.

**Comment by djivani** [comment] 2016-07-21 16:08
You can use OpenCV to do this. From what I have tried, saving raw RGB is the best bet if you want to maintain the frame-rate, especially if you are working with multiple kinects. At 15fps and 7-8MB/image a SSD should work fine. A HDD might be okay too for just one kinect.:
`cv::Mat(rgb->height, rgb->width, CV_8UC4, rgb->data).copyTo(rgbMat);`
`ss << "Path/image"<<framecount<<".bmp";`
`filename = ss.str();`
`cv::imwrite(filename.c_str(), rgbMat);`

**Comment by robozo** [comment] 2016-07-23 11:35
this issue is a duplicate of #438, #551 and probably can be closed.
the newest version of libfreenect2 apparently has some data logging functions,
but i want a custom data format, so am reinventing the wheel (again).

**Comment by xlz** [comment] 2016-08-09 04:31
Recording with OpenCV, or ROS, or handrolled compression libraries. The big issue is it's just too big for something that is included by default to be useful for everyone. I have plans for such a tool but it's too big to make it useful so far.

**Comment by robozo** [comment] 2016-08-09 07:13
just a note, writing out the point cloud to a SSD was not a problem, on a 2.9 GHz mac laptop
running 10.8.5 even with a browser, etc. open.

while(!protonect_shutdown)
  {
  ...
  write(fd,Mydepth,4*512*424);
  write(fd,Mycolor,3*512*424);
  ...
  }

ran fine at 30 fps, haven't tested what limits are.  SSD's are fast!  they just fill up fast...

**Comment by xlz** [comment] 2016-12-05 19:03
Merge into #438.

**Closed** 2016-12-05 19:04 UTC
