### ISSUE TITLE
Kinect One locks USB devices

### ISSUE THREAD

**Issue by digitalmeltingculture** [OpenKinect/libfreenect2#962] opened 2018-01-21 17:02 UTC
When I switch the PC on with the Kinect already plugged on, the other USB devices (mouse, keyboard, etc...) do not work.

I cannot manually plug the Kinect after the PC boot. I need to have the Kinect already plugged on when the PC boots. Does anyone have the same need?
How could I solve this?
I already tried to use an external powered USB switch but it did not solve the issue (i used an ADJ USB 3.0 powered hub).

**Comment by xlz** [comment] 2018-01-23 05:29
Your OS? Any logs?

**Comment by digitalmeltingculture** [comment] 2018-01-23 19:43
The OS is Ubuntu Studio. I had the same problem both on 16.04 and 17.04.
I have not any log about that. How could I log the USB ports behaviour?

Il 23 gen 2018 6:29 AM, "Lingzhu Xiang" <notifications@github.com> ha
scritto:

**Comment by digitalmeltingculture** [comment] 2018-01-27 10:19
I also tried to set the USB autosuspend to -1 as suggested in the specifics, but it does not improve the status.
@xlz how could I report the logs you asked?

**Comment by xlz** [comment] 2018-01-30 16:44
Duplicate of #940.

**Closed by xlz** 2018-01-30 16:44 UTC
