### ISSUE TITLE
[bug] bilateral filter = false, edge aware filter = true gives invalid depth

### ISSUE THREAD

**Issue by fishcu** [OpenKinect/libfreenect2#1087] opened 2019-08-21 10:19 UTC
Consider the following snippet of code:

```
libfreenect2::Freenect2Device::Config config;
  config.MinDepth = 0.5f;
  config.MaxDepth = 4.5f;
  config.EnableBilateralFilter = false;
  config.EnableEdgeAwareFilter = true;
  device_handle->setConfiguration(config);
```

This will produce an invalid depth output. I have attached an example of such an output (after rgb->depth registration). Note that the float image has been converted to RGB via Matlab's "jet" color map.
![kinect_depth_map](https://user-images.githubusercontent.com/25356186/63423922-9b432a80-c40d-11e9-82ea-34394bfbfbd1.png)

I have tried the following other combinations:
- bilateral = true, edge aware = true
- bilateral = true, edge aware = false
- bilateral = false, edge aware = false

And they all work.

Thus I suspect this is a bug in the driver, possibly caused by the edge aware filter using some temporary output buffer of the bilateral filter even if it is valid?

**Comment by fishcu** [comment] 2019-08-21 10:22
Here's an example with both filters enabled, to show that the rest of the code works:

![kinect_depth_map](https://user-images.githubusercontent.com/25356186/63424239-481da780-c40e-11e9-8859-b3be63305e86.png)

**Comment by xlz** [comment] 2019-09-27 09:49
> the edge aware filter using some temporary output buffer of the bilateral filter

It is the case.

Duplicate of #163.

**Closed by xlz** 2019-09-27 09:49 UTC
