### ISSUE TITLE
Build failed when running sh install_ubuntu.sh

### ISSUE THREAD

**Issue by SamTew** [OpenKinect/libfreenect2#305] opened 2015-06-23 15:42 UTC
Here is my output. Can anyone help me to solve?

sam@sam-X450LCP:~/libfreenect2/depends$ sh install_ubuntu.sh
--2015-06-23 23:39:34--  http://archive.ubuntu.com/ubuntu/pool/universe/g/glfw3/libglfw3_3.0.4-1_amd64.deb
Resolving archive.ubuntu.com (archive.ubuntu.com)... 91.189.91.15, 91.189.91.13, 91.189.92.201, ...
Connecting to archive.ubuntu.com (archive.ubuntu.com)|91.189.91.15|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 33000 (32K) [application/x-debian-package]
Server file no newer than local file ‘libglfw3_3.0.4-1_amd64.deb’ -- not retrieving.

--2015-06-23 23:39:35--  http://archive.ubuntu.com/ubuntu/pool/universe/g/glfw3/libglfw3-dev_3.0.4-1_amd64.deb
Resolving archive.ubuntu.com (archive.ubuntu.com)... 91.189.91.13, 91.189.92.201, 91.189.91.24, ...
Connecting to archive.ubuntu.com (archive.ubuntu.com)|91.189.91.13|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 19168 (19K) [application/x-debian-package]
Server file no newer than local file ‘libglfw3-dev_3.0.4-1_amd64.deb’ -- not retrieving.

Cloning into '/home/sam/libfreenect2/depends/libusb_src'...
remote: Counting objects: 10776, done.
remote: Total 10776 (delta 0), reused 0 (delta 0), pack-reused 10776
Receiving objects: 100% (10776/10776), 2.61 MiB | 873.00 KiB/s, done.
Resolving deltas: 100% (7935/7935), done.
Checking connectivity... done.
Note: checking out '51b10191033ca3a3819dcf46e1da2465b99497c2'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 51b1019... linux_usbfs: Update MAX_ISO_BUFFER_LENGTH
libtoolize: putting auxiliary files in `.'.
libtoolize: copying file `./ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: copying file `m4/libtool.m4'
libtoolize: copying file `m4/ltoptions.m4'
libtoolize: copying file `m4/ltsugar.m4'
libtoolize: copying file `m4/ltversion.m4'
libtoolize: copying file `m4/lt~obsolete.m4'
configure.ac:4: installing './compile'
configure.ac:4: installing './config.guess'
configure.ac:4: installing './config.sub'
configure.ac:2: installing './install-sh'
configure.ac:2: installing './missing'
Makefile.am: installing './depcomp'
libtoolize: putting auxiliary files in `.'.
libtoolize: copying file `./ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: copying file `m4/libtool.m4'
libtoolize: copying file `m4/ltoptions.m4'
libtoolize: copying file `m4/ltsugar.m4'
libtoolize: copying file `m4/ltversion.m4'
libtoolize: copying file `m4/lt~obsolete.m4'
configure.ac:38: installing './compile'
configure.ac:39: installing './config.guess'
configure.ac:39: installing './config.sub'
configure.ac:29: installing './install-sh'
configure.ac:29: installing './missing'
examples/Makefile.am: installing './depcomp'
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking whether make supports nested variables... (cached) yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for windres... no
checking for inline... inline
checking operating system... Linux
checking for library containing clock_gettime... none required
checking libudev.h usability... yes
checking libudev.h presence... yes
checking for libudev.h... yes
checking for udev_new in -ludev... yes
checking poll.h usability... yes
checking poll.h presence... yes
checking for poll.h... yes
checking sys/timerfd.h usability... yes
checking sys/timerfd.h presence... yes
checking for sys/timerfd.h... yes
checking whether TFD_NONBLOCK is declared... yes
checking whether to use timerfd for timing... yes
checking for struct timespec... yes
checking syslog.h usability... yes
checking syslog.h presence... yes
checking for syslog.h... yes
checking for syslog... yes
checking for sigaction... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking for gettimeofday... yes
checking signal.h usability... yes
checking signal.h presence... yes
checking for signal.h... yes
checking whether CC supports -std=gnu99... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating libusb-1.0.pc
config.status: creating Makefile
config.status: creating libusb/Makefile
config.status: creating examples/Makefile
config.status: creating tests/Makefile
config.status: creating doc/Makefile
config.status: creating doc/doxygen.cfg
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands
make  all-recursive
make[1]: Entering directory `/home/sam/libfreenect2/depends/libusb_src'
Making all in libusb
make[2]: Entering directory `/home/sam/libfreenect2/depends/libusb_src/libusb'
make[3]: Entering directory `/home/sam/libfreenect2/depends/libusb_src/libusb'
  CC       libusb_1_0_la-core.lo
  CC       libusb_1_0_la-descriptor.lo
  CC       libusb_1_0_la-io.lo
  CC       libusb_1_0_la-strerror.lo
  CC       libusb_1_0_la-sync.lo
  CC       libusb_1_0_la-hotplug.lo
  CC       os/libusb_1_0_la-threads_posix.lo
  CC       os/libusb_1_0_la-linux_usbfs.lo
  CC       os/libusb_1_0_la-poll_posix.lo
  CC       os/libusb_1_0_la-linux_udev.lo
  CCLD     libusb-1.0.la
make[3]: Leaving directory `/home/sam/libfreenect2/depends/libusb_src/libusb'
make[2]: Leaving directory `/home/sam/libfreenect2/depends/libusb_src/libusb'
Making all in doc
make[2]: Entering directory `/home/sam/libfreenect2/depends/libusb_src/doc'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/home/sam/libfreenect2/depends/libusb_src/doc'
make[2]: Entering directory `/home/sam/libfreenect2/depends/libusb_src'
make[2]: Leaving directory `/home/sam/libfreenect2/depends/libusb_src'
make[1]: Leaving directory `/home/sam/libfreenect2/depends/libusb_src'
Making install in libusb
make[1]: Entering directory `/home/sam/libfreenect2/depends/libusb_src/libusb'
make[2]: Entering directory `/home/sam/libfreenect2/depends/libusb_src/libusb'
make[3]: Entering directory `/home/sam/libfreenect2/depends/libusb_src/libusb'
 /bin/mkdir -p '/home/sam/libfreenect2/depends/libusb/lib'
 /bin/bash ../libtool   --mode=install /usr/bin/install -c   libusb-1.0.la '/home/sam/libfreenect2/depends/libusb/lib'
libtool: install: /usr/bin/install -c .libs/libusb-1.0.so.0.1.0 /home/sam/libfreenect2/depends/libusb/lib/libusb-1.0.so.0.1.0
libtool: install: (cd /home/sam/libfreenect2/depends/libusb/lib && { ln -s -f libusb-1.0.so.0.1.0 libusb-1.0.so.0 || { rm -f libusb-1.0.so.0 && ln -s libusb-1.0.so.0.1.0 libusb-1.0.so.0; }; })
libtool: install: (cd /home/sam/libfreenect2/depends/libusb/lib && { ln -s -f libusb-1.0.so.0.1.0 libusb-1.0.so || { rm -f libusb-1.0.so && ln -s libusb-1.0.so.0.1.0 libusb-1.0.so; }; })
libtool: install: /usr/bin/install -c .libs/libusb-1.0.lai /home/sam/libfreenect2/depends/libusb/lib/libusb-1.0.la
libtool: install: /usr/bin/install -c .libs/libusb-1.0.a /home/sam/libfreenect2/depends/libusb/lib/libusb-1.0.a
libtool: install: chmod 644 /home/sam/libfreenect2/depends/libusb/lib/libusb-1.0.a
libtool: install: ranlib /home/sam/libfreenect2/depends/libusb/lib/libusb-1.0.a
libtool: finish: PATH="/opt/ros/indigo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/sbin" ldconfig -n /home/sam/libfreenect2/depends/libusb/lib
----------------------------------------------------------------------
Libraries have been installed in:
   /home/sam/libfreenect2/depends/libusb/lib

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the `-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the `LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the `LD_RUN_PATH' environment variable
     during linking
   - use the `-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to `/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
 /bin/mkdir -p '/home/sam/libfreenect2/depends/libusb/include/libusb-1.0'
 /usr/bin/install -c -m 644 libusb.h '/home/sam/libfreenect2/depends/libusb/include/libusb-1.0'
make[3]: Leaving directory `/home/sam/libfreenect2/depends/libusb_src/libusb'
make[2]: Leaving directory `/home/sam/libfreenect2/depends/libusb_src/libusb'
make[1]: Leaving directory `/home/sam/libfreenect2/depends/libusb_src/libusb'
Making install in doc
make[1]: Entering directory `/home/sam/libfreenect2/depends/libusb_src/doc'
make[2]: Entering directory `/home/sam/libfreenect2/depends/libusb_src/doc'
make[2]: Nothing to be done for `install-exec-am'.
make[2]: Nothing to be done for `install-data-am'.
make[2]: Leaving directory `/home/sam/libfreenect2/depends/libusb_src/doc'
make[1]: Leaving directory `/home/sam/libfreenect2/depends/libusb_src/doc'
make[1]: Entering directory `/home/sam/libfreenect2/depends/libusb_src'
make[2]: Entering directory `/home/sam/libfreenect2/depends/libusb_src'
make[2]: Nothing to be done for `install-exec-am'.
 /bin/mkdir -p '/home/sam/libfreenect2/depends/libusb/lib/pkgconfig'
 /usr/bin/install -c -m 644 libusb-1.0.pc '/home/sam/libfreenect2/depends/libusb/lib/pkgconfig'
make[2]: Leaving directory `/home/sam/libfreenect2/depends/libusb_src'
make[1]: Leaving directory `/home/sam/libfreenect2/depends/libusb_src'

Execute the following commands to install the remaining dependencies (if you have not already done so):

sudo dpkg -i libglfw3*_3.0.4-1_*.deb
sudo apt-get install build-essential libturbojpeg libjpeg-turbo8-dev libtool autoconf libudev-dev cmake mesa-common-dev freeglut3-dev libxrandr-dev doxygen libxi-dev libopencv-dev automake
sudo apt-get install libturbojpeg0-dev # (Debian)

**Comment by floe** [comment] 2015-06-23 18:02
The script did exactly what it's supposed to - I don't see any error message.

**Comment by floe** [comment] 2015-06-25 08:29
Closing - not a bug.

**Closed by floe** 2015-06-25 08:29 UTC
